name: Update IP list

on:
    workflow_dispatch: {}
    push:
        branches:
            - main
    schedule:
        - cron: "0 1 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Create .env file
              run: |
                  touch .env
            - name: Build
              run: |
                  docker compose build
            - name: Update
              run: |
                  docker compose run update
            - name: Copy artifacts
              run: |
                  cp ${{ github.workspace }}/tmp/ipcat/* ${{ github.workspace }}
            - name: Commit changes to IP list
              run: |
                  git config --global user.name "kanadaj"
                  git config --global user.email "kanadaj@users.noreply.github.com"
                  git add ./datacenters.csv ./datacenters-stats.csv
                  git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
                  git push
